// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz7ghgbJf-v-W6W8V5aQ4ircLTbIHDPOQ',
    appId: '1:151583418392:web:ae5960b997ee9a6636fb6d',
    messagingSenderId: '151583418392',
    projectId: 'news-soldier',
    authDomain: 'news-soldier.firebaseapp.com',
    storageBucket: 'news-soldier.appspot.com',
    measurementId: 'G-H2QQ8BB1TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfnKIh2g9N8fhnDqSzs3eXGLFONbwFQh0',
    appId: '1:151583418392:android:668b54eaecea80cf36fb6d',
    messagingSenderId: '151583418392',
    projectId: 'news-soldier',
    storageBucket: 'news-soldier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-3E49oEKcvDVi63GgZU430wjNw1kxuzk',
    appId: '1:151583418392:ios:261ae8deaaf7720636fb6d',
    messagingSenderId: '151583418392',
    projectId: 'news-soldier',
    storageBucket: 'news-soldier.appspot.com',
    iosClientId: '151583418392-b3n37t8nmqas9902h661pvph9attt11v.apps.googleusercontent.com',
    iosBundleId: 'com.soldier.news',
  );
}
